# Generated by Django 3.1.5 on 2021-01-24 11:37

import blogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210122_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='django.png', upload_to=blogapp.models.user_directory_path),
        ),
    ]
